#!/bin/bash
set -eou pipefail

cd infrastructure
yarn install

case "${TRAVIS_BRANCH}" in
    "master")
        STACK_NAME="staging"
        ;;
    "production")
        STACK_NAME="production"
        ;;
    *)
        echo "not deploying as TRAVIS_BRANCH is not 'master' or 'production'"
        exit 0
        ;;
esac

pulumi stack select "pulumi/get-pulumi-com-${STACK_NAME}"

echo "Deploying stack 'pulumi/get-pulumi-com-${STACK_NAME}'. Current user:"
aws sts get-caller-identity

case "${TRAVIS_EVENT_TYPE}" in
    "push")
        pulumi update --yes
        ;;
    "pull_request")
        pulumi preview --diff
        ;;
    *)
        echo "ignoring ${TRAVIS_EVENT_TYPE} from travis"
        ;;
esac
