name: Staging
on:
  push:
    branches:
      - master
jobs:

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: infrastructure
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
        role-duration-seconds: 3600
        role-session-name: get.pulumi.com-${{ github.run_id }}
    - run: yarn install
      working-directory: infrastructure
    - uses: pulumi/actions@8582a9e8cc630786854029b4e09281acd6794b58 # v6
      with:
        command: up
        stack-name: "pulumi/get-pulumi-com/staging"
        work-dir: infrastructure
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
