name: Production
on:
  push:
    branches:
      - production
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: "./dist"
  install:
    name: Install & Test
    strategy:
      matrix:
        os: [ "ubuntu", "macos" ]
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install chef
      uses: actionshub/chef-install@master
      with:
        channel: current
        project: inspec
    - name: accept chef license
      run: |
        inspec --chef-license=accept-silent
    - name: Run install script
      run: |
        ./dist/install.sh --silent
    - name: Run inspec
      run: |
        inspec exec spec/inspec/
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    steps:
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME_PRODUCTION }}
        role-external-id: "pulumi/get-pulumi-com/production"
        role-duration-seconds: 3600
        role-session-name: get.pulumi.com-${{ github.run_id }}
    - run: yarn install
      working-directory: infrastructure
    - uses: pulumi/actions@v3
      with:
        command: up
        stack-name: "pulumi/get-pulumi-com/production"
        work-dir: infrastructure
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
