name: pull-request
on: pull_request

permissions:
  id-token: write # "write" means you can fetch OIDC tokens

jobs:

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  preview:
    name: Preview
    runs-on: ubuntu-latest
    env:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
    steps:
    - if: github.base_ref == 'production'
      run: |
          echo "AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME_PRODUCTION }}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-external-id: ${{ env.PULUMI_STACK_NAME }}
        role-duration-seconds: 3600
        role-session-name: get.pulumi.com-${{ github.run_id }}
        unset-current-credentials: true
    - run: yarn install
      working-directory: infrastructure
    - if: github.base_ref == 'production'
      uses: pulumi/actions@v4
      with:
        command: preview
        work-dir: infrastructure
        stack-name: "pulumi/get-pulumi-com/production"
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - if: github.base_ref == 'master'
      uses: pulumi/actions@v4
      with:
        command: preview
        work-dir: infrastructure
        stack-name: "pulumi/get-pulumi-com/staging"
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
