name: pull-request
on: pull_request
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: "./dist"
  install:
    name: Install & Test
    strategy:
      matrix:
        os: [ "ubuntu", "macos" ]
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install chef
      uses: actionshub/chef-install@master
      with:
        channel: current
        project: inspec
    - name: accept chef license
      run: |
        inspec --chef-license=accept-silent
    - name: Run install script
      run: |
        ./dist/install.sh --silent
    - name: Run inspec
      run: |
        inspec exec spec/inspec/
  preview:
    name: Preview
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure
    env:
      PULUMI_STACK_NAME: "pulumi/get-pulumi-com/staging"
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
    steps:
    - if: github.ref == 'refs/heads/production'
      run: |
          echo "PULUMI_STACK_NAME=pulumi/get-pulumi-com/production" >> $GITHUB_ENV
          echo "AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME_PRODUCTION }}" >> $GITHUB_ENV      
    - uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-external-id: ${{ env.PULUMI_STACK_NAME }}
        role-duration-seconds: 3600
        role-session-name: get.pulumi.com-${{ github.run_id }}
    - uses: pulumi/actions@v1
      with:
        command: preview
      env:
          PULUMI_ROOT: infrastructure
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          IS_PR_WORKFLOW: true
