permissions: write-all # Equivalent to default permissions plus id-token: write
env:
  ESC_ACTION_OIDC_AUTH: true
  ESC_ACTION_OIDC_ORGANIZATION: pulumi
  ESC_ACTION_OIDC_REQUESTED_TOKEN_TYPE: urn:pulumi:token-type:access_token:organization
  ESC_ACTION_ENVIRONMENT: github-secrets/pulumi-get.pulumi.com
  ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: false
name: pull-request
on: pull_request

jobs:

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      ESC_ACTION_EXPORT_ENVIRONMENT_VARIABLES: AWS_ROLE_TO_ASSUME=AWS_ROLE_TO_ASSUME_STAGING
    steps:
    - name: Fetch secrets from ESC
      id: esc-secrets
      uses: pulumi/esc-action@v1
    - if: github.base_ref == 'production'
      run: |
          echo "AWS_ROLE_TO_ASSUME=${{ steps.esc-secrets.outputs.AWS_ROLE_TO_ASSUME_PRODUCTION }}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 3600
        role-session-name: get.pulumi.com-${{ github.run_id }}
    - run: yarn install
      working-directory: infrastructure
    - if: github.base_ref == 'production'
      uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d # v7
      with:
        command: preview
        work-dir: infrastructure
        stack-name: "pulumi/get-pulumi-com/production"
      env:
          PULUMI_ACCESS_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_ACCESS_TOKEN }}
    - if: github.base_ref == 'master'
      uses: pulumi/actions@8e5e406f4007fca908480587cb9893c07090f58d # v7
      with:
        command: preview
        work-dir: infrastructure
        stack-name: "pulumi/get-pulumi-com/staging"
      env:
        PULUMI_ACCESS_TOKEN: ${{ steps.esc-secrets.outputs.PULUMI_ACCESS_TOKEN }}
