on:
  pull_request:

name: 'Trigger: Pull Request'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      with:
        scandir: "./dist"
  install:
    name: Run install script
    strategy:
      matrix:
        os: [ "ubuntu", "macos" ]
    runs-on: ${{matrix.os}}-latest
    steps:
    - uses: actions/checkout@v2
    - name: install chef
      uses: actionshub/chef-install@master
      with:
        channel: current
        project: inspec
    - name: Run install script
      run: |
        ./dist/install.sh --silent
    - name: Run inspec
      run: |
        inspec --chef-license=accept exec spec/inspec/
