name: pull-request
on: pull_request

jobs:

  tests:
    name: Tests
    uses: ./.github/workflows/tests.yml

  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME_STAGING }}
    steps:
    - if: github.base_ref == 'production'
      run: |
          echo "AWS_ROLE_TO_ASSUME=${{ secrets.AWS_ROLE_TO_ASSUME_PRODUCTION }}" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-west-2
        role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 3600
        role-session-name: get.pulumi.com-${{ github.run_id }}
    - run: yarn install
      working-directory: infrastructure
    - if: github.base_ref == 'production'
      uses: pulumi/actions@8582a9e8cc630786854029b4e09281acd6794b58 # v6
      with:
        command: preview
        work-dir: infrastructure
        stack-name: "pulumi/get-pulumi-com/production"
      env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
    - if: github.base_ref == 'master'
      uses: pulumi/actions@8582a9e8cc630786854029b4e09281acd6794b58 # v6
      with:
        command: preview
        work-dir: infrastructure
        stack-name: "pulumi/get-pulumi-com/staging"
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
