on: 
  workflow_dispatch:

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        scandir: "./dist"

  install:
    name: Install & Test

    strategy:
      fail-fast: false
      matrix:
        os: [ "ubuntu", "macos" ]
    runs-on: ${{matrix.os}}-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run install script
      run: |
        ./dist/install.sh --silent
    - name: Check installed content
      run: |
        test -d ~/.pulumi
        test -d ~/.pulumi/bin
        cd ~/.pulumi/bin
        exit_code=0
        echo "Checking expected files are nonzero, readable, and executable"
        for f in \
          "pulumi" \
          "nonexistent" \
          "pulumi-analyzer-policy" \
          "pulumi-analyzer-policy-python" \
          "pulumi-language-dotnet" \
          "pulumi-language-go" \
          "pulumi-language-nodejs" \
          "pulumi-language-python" \
          "pulumi-language-python-exec" \
          "pulumi-language-yaml" \
          "pulumi-resource-pulumi-nodejs" \
          "pulumi-resource-pulumi-python" \
          "pulumi-watch"; do
          if test -s "$f" -a -r "$f" -a ! -x "$f"; then
            echo "OK: $f"
          else 
            echo "FAIL: $f"
            echo "  ls -al: $(ls -al $f)"
            echo 
            exit_code=1
          fi
        done
        exit $exit_code
